accountapp/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView
from accountapp.views import AccountCreateView, AccountDeleteView, AccountDetailView, AccountUpdateView, hello_world

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'), 

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), 
    path('logout/', LogoutView.as_view(), name='logout'), 

    path('create/', AccountCreateView.as_view(), name='create'), 
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), 
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'), 
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'), 
]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleListView, ArticleUpdateView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pinterest_clone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'SCDream3';">
<!-- <body> -->
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pinterest_footer">
    <div class="pinterest_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pinterest_logo">Pinterest</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>test1</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&family=Noto+Sans+KR:wght@100;300&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>

        @font-face {
            font-family: 'SCDream1';
            src: local('SCDream1'),
            url("{% static 'fonts/SCDream1.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'SCDream3';
            src: local('SCDream3'),
            url("{% static 'fonts/SCDream3.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'SCDream9';
            src: local('SCDream9'),
            url("{% static 'fonts/SCDream9.otf' %}") format("opentype");
        }

    </style>
</head>

templates/header.html
<div class="pinterest_header">
    <div>
        <h1 class="pinterest_logo">Pinterest</h1>
    </div>
    <div>
        <a href="{% url 'articleapp:list' %}">
            <span>articles</span>
        </a>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>Mypage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>